# -*- coding: utf-8 -*-
"""ai.py

cdAutomatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNodl2lGrU9EgC1_xQCOQpQRQIMmP9I7
"""

import os
import streamlit as st
api_key = os.getenv("GROQ_API_KEY")
from docx import Document
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate


# -----------------------------------------------
# Streamlit Page Setup
# -----------------------------------------------
st.set_page_config(page_title="AI Assignment Checker", page_icon="📚", layout="centered")
st.title("📘 AI Assignment Checker")
st.write("Easily detect AI-generated assignments and auto-grade them using multiple AI models (via ChatGroq + LangChain).")

# -----------------------------------------------
# Input Section
# -----------------------------------------------
teacher_question = st.text_area("🎯 Enter the teacher's question:")
uploaded_file = st.file_uploader("📂 Upload student's assignment (.txt or .docx):", type=["txt", "docx"])

# -----------------------------------------------
# File Reader
# -----------------------------------------------
def read_assignment(file):
    ext = os.path.splitext(file.name)[1].lower()
    if ext == ".txt":
        return file.read().decode("utf-8")
    elif ext == ".docx":
        doc = Document(file)
        return "\n".join(p.text for p in doc.paragraphs)
    return ""

# -----------------------------------------------
# Models (via Groq)
# -----------------------------------------------
def get_models():
    return {
        "LLaMA-3-8B": ChatGroq(model="llama-3.1-8b-instant", temperature=0),
        "Mixtral-8x7B": ChatGroq(model="openai/gpt-oss-120b", temperature=0),
        "LLaMA-3.1-8B": ChatGroq(model="llama-3.1-8b-instant", temperature=0),
        "LLaMA-3-70B": ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
    }

# -----------------------------------------------
# Prompts
# -----------------------------------------------
ai_check_prompt = ChatPromptTemplate.from_template("""
You are an expert content detector.
Tell me how much of this text seems AI-generated (0 to 100%) and explain briefly.

Student's Answer:
{text}
""")

marking_prompt = ChatPromptTemplate.from_template("""
You are a teacher. Based on the given question and student's answer,
give marks out of 10 and explain why.

Question: {question}
Answer: {answer}
""")

# -----------------------------------------------
# Analyzer
# -----------------------------------------------
def analyze_assignment(question, answer):
    models = get_models()
    ai_scores = {}
    marks = {}

    for name, model in models.items():
        st.write(f"🔹 Evaluating with {name}...")
        try:
            ai_chain = ai_check_prompt | model
            mark_chain = marking_prompt | model

            ai_result = ai_chain.invoke({"text": answer}).content
            mark_result = mark_chain.invoke({"question": question, "answer": answer}).content

            ai_scores[name] = ai_result
            marks[name] = mark_result
        except Exception as e:
            ai_scores[name] = f"Error: {e}"
            marks[name] = f"Error: {e}"

    return ai_scores, marks

# -----------------------------------------------
# Simple Extract Numbers (heuristic)
# -----------------------------------------------
import re
def extract_number(text):
    nums = re.findall(r"\d+", text)
    if nums:
        n = int(nums[0])
        if n > 10: n = 10
        return n
    return 0

# -----------------------------------------------
# Main Execution
# -----------------------------------------------
if uploaded_file and teacher_question:
    text = read_assignment(uploaded_file)
    st.subheader("📄 Assignment Preview")
    st.text_area("Extracted Content", text[:1500] + ("..." if len(text) > 1500 else ""), height=250)

    if st.button("🚀 Evaluate Assignment"):
        with st.spinner("Analyzing with 4 models... please wait ⏳"):
            ai_scores, mark_results = analyze_assignment(teacher_question, text)

        st.success("✅ Done! Here's the result:")

        total_ai, total_marks, count = 0, 0, 0

        for name in ai_scores.keys():
            with st.expander(f"🧩 {name}"):
                st.markdown("*AI Detection Result:*")
                st.write(ai_scores[name])
                st.markdown("*Marks Evaluation:*")
                st.write(mark_results[name])

                ai_val = extract_number(ai_scores[name])
                mark_val = extract_number(mark_results[name])
                total_ai += ai_val
                total_marks += mark_val
                count += 1

        if count > 0:
            avg_ai = total_ai / count
            avg_marks = total_marks / count
        else:
            avg_ai = 0
            avg_marks = 0

        if avg_ai > 65:
            verdict = "🧠 Mostly AI-generated"
        elif avg_ai > 40:
            verdict = "⚖️ Possibly AI-assisted"
        else:
            verdict = "🧍‍♂️ Mostly Human-written"

        st.subheader("📊 Final Evaluation Summary")
        st.write(f"*Final Verdict:* {verdict}")
        st.write(f"*Average AI Probability:* {avg_ai:.2f}%")
        st.write(f"*Average Marks (out of 10):* {avg_marks:.2f}")

        st.bar_chart({"AI Probability (%)": [avg_ai], "Marks (out of 10)": [avg_marks]})
else:
    st.info("✍️ Enter the teacher's question and upload the assignment to start.")

